<?php
/**
 * Created by PhpStorm.
 * User: SGH
 * Date: 10/19/2017
 * Time: 11:16 PM
 */

namespace app\modules\admin\controllers;

use yii\web\Controller;
use yii\filters\AccessControl;

class AppAdminController extends Controller

{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]

                ]
            ]
        ];

        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}